### ISSUE TITLE
Stress level tracking/management flowchart

### ISSUE THREAD

**Issue by anasatryan** [anasatryan/Serendipity#1]
![0F0493EA-C0CF-4E21-81FE-0228FC540E3D](https://user-images.githubusercontent.com/61308440/75049632-fef50000-54e3-11ea-906a-aa0cd99ca57b.jpeg)
![4E570A0A-AE28-4DEE-AD0E-4CA724B46C82](https://user-images.githubusercontent.com/61308440/75049643-03211d80-54e4-11ea-9407-292b895aa16b.jpeg)

**Comment by victoriaharutyunyan** [comment]
Firstly, your flow chart must contain operations in python language. 
Secondly, I think that you should more concentrate on the case when your user's stress is not created by the three things you mentioned, but other thing and you should handle that "other" case.
